In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sqlalchemy import create_engine

In [12]:
engine = create_engine(
    "postgresql+psycopg2://postgres:admin123@localhost:5432/sales_analytics"
)

print("Connected Successfully")

Connected Successfully

In [3]:
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema='public';
"""

tables = pd.read_sql(query, engine)

tables

           table_name
0             product
1            reseller
2              region
3         salesperson
4  salesperson_region
5             targets
6               sales

In [4]:
product = pd.read_csv(
    "product.csv",
    sep="\t"
)

print(product.columns.tolist())

['ProductKey', 'Product', 'Standard Cost', 'Color', 'Subcategory', 'Category', 'Background Color Format', 'Font Color Format']

In [5]:
product.columns = [
    "product_key",
    "product_name",
    "standard_cost",
    "color",
    "subcategory",
    "category",
    "background_color_format",
    "font_color_format"
]

In [6]:
product["standard_cost"] = (
    product["standard_cost"]
    .replace(r'[\$,]', '', regex=True)
    .astype(float)
)

In [ ]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:admin123@localhost:5432/sales_analytics"
)

product.to_sql(
    "product",
    engine,
    if_exists="append",
    index=False
)

print("Product Loaded Successfully")

In [17]:
Query = """
SELECT COUNT(*)
FROM product;
""" 
result = pd.read_sql(Query, engine)
print(result)

   count
0    397

In [18]:
Reseller = pd.read_csv(
    "Reseller.csv",
    sep="\t"
)
print(Reseller.columns.tolist())

['ResellerKey', 'Business Type', 'Reseller', 'City', 'State-Province', 'Country-Region']

In [20]:
Reseller.columns = [
    "reseller_key",
    "business_type",
    "reseller_name",
    "city",
    "state_province",
    "country_region"
]

Reseller.to_sql(
    "reseller",
    engine,
    if_exists="append",
    index=False
)

701

In [ ]:
region = pd.read_csv(
    "Region.csv",
    sep="\t"
)


region.columns = [
    "sales_territory_key",
    "region_name",
    "country",
    "region_group"
]


print("Region Loaded")

print(region.columns.tolist())

region.to_sql(
    "region",
    engine,
    if_exists="append",
    index=False
)

print("Region Loaded Successfully")

In [31]:
query = """SELECT COUNT(*)
FROM region;"""
result = pd.read_sql(query, engine)
print(result)

   count
0     10

In [39]:
Salesperson = pd.read_csv("Salesperson.csv", 
                          sep="\t")

Salesperson.columns = [
    "employee_key",
    "employee_id",
    "salesperson_name",
    "title",
    "upn"
]

Salesperson.to_sql(
    "salesperson",
    engine,
    if_exists="append",
    index=False
)

print("Salesperson Loaded")

Salesperson Loaded

In [ ]:
query = """SELECT *
FROM Salesperson;"""
result = pd.read_sql(query, engine)
print(result)

In [41]:
salesperson_region = pd.read_csv("SalespersonRegion.csv", 
                                 sep="\t")

salesperson_region.columns = [
    "employee_key",
    "sales_territory_key"
]

salesperson_region.to_sql(
    "salesperson_region",
    engine,
    if_exists="append",
    index=False
)

print("Salesperson Region Loaded")

Salesperson Region Loaded

In [42]:
targets = pd.read_csv("Targets.csv", 
                       sep="\t")

targets.columns = [
    "employee_id",
    "target_amount",
    "target_month"
]

targets["target_amount"] = (
    targets["target_amount"]
    .replace(r'[\$,]', '', regex=True)
    .astype(float)
)

targets["target_month"] = pd.to_datetime(
    targets["target_month"]
)

targets.to_sql(
    "targets",
    engine,
    if_exists="append",
    index=False
)

print("Targets Loaded")

Targets Loaded

In [43]:
sales = pd.read_csv("Sales.csv", 
                     sep="\t")

sales.columns = [
    "sales_order_number",
    "order_date",
    "product_key",
    "reseller_key",
    "employee_key",
    "sales_territory_key",
    "quantity",
    "unit_price",
    "sales_amount",
    "cost_amount"
]

sales["unit_price"] = (
    sales["unit_price"]
    .replace(r'[\$,]', '', regex=True)
    .astype(float)
)

sales["sales_amount"] = (
    sales["sales_amount"]
    .replace(r'[\$,]', '', regex=True)
    .astype(float)
)

sales["cost_amount"] = (
    sales["cost_amount"]
    .replace(r'[\$,]', '', regex=True)
    .astype(float)
)

sales["order_date"] = pd.to_datetime(
    sales["order_date"]
)

sales.to_sql(
    "sales",
    engine,
    if_exists="append",
    index=False
)

print("Sales Loaded")

Sales Loaded

In [51]:
import pandas as pd

def profile_table(df):

    profile = pd.DataFrame({
        "Column": df.columns,
        "DataType": df.dtypes.values,
        "NullCount": df.isnull().sum().values,
        "UniqueCount": df.nunique().values,
        "DuplicateCount": [df[col].duplicated().sum() for col in df.columns]
    })

    profile["NullPercent"] = (
        profile["NullCount"] / len(df) * 100
    ).round(2)

    return profile.sort_values(
        by="UniqueCount",
        ascending=True
    )

# Example
profile_table(product)

,Column,DataType,NullCount,UniqueCount,DuplicateCount,NullPercent
7,font_color_format,str,0,2,395,0.00
5,category,str,0,4,393,0.00
3,color,str,56,9,387,14.11
6,background_color_format,str,0,10,387,0.00
4,subcategory,str,0,37,360,0.00
2,standard_cost,float64,0,131,266,0.00
1,product_name,str,0,295,102,0.00
0,product_key,int64,0,397,0,0.00

In [ ]:
profile_table(sales)
profile_table(Reseller)

,Column,DataType,NullCount,UniqueCount,DuplicateCount,NullPercent
1,business_type,str,0,3,698,0.0
5,country_region,str,0,6,695,0.0
4,state_province,str,0,65,636,0.0
3,city,str,0,451,250,0.0
2,reseller_name,str,0,699,2,0.0
0,reseller_key,int64,0,701,0,0.0